version: '3.8'
services:
  wireguard-vpn:
    build:
      context: .
      dockerfile: docker/Dockerfile.wireguard
      platforms: [linux/arm64]
    container_name: wireguard-server
    restart: unless-stopped
    privileged: true
    platform: linux/arm64
    environment:
      - WG_HOST=auto
      - WG_PORT=51820
    ports:
      - "51820:51820/udp"
    volumes:
      - ./config/wireguard:/etc/wireguard
      - ./client-configs:/app/client-configs
      - ./logs:/var/log/wireguard
      - ./scripts:/app/scripts
    cap_add: [NET_ADMIN, SYS_MODULE]
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks: [vpn-network]
networks:
  vpn-network:
